<a href="https://colab.research.google.com/github/ys23-lys/ESAA/blob/main/ESAA_OB_WEEK4_%ED%95%84%EC%82%AC2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[내용 정리]**

## 07. 행렬 분해를 이용한 잠재 요인 협업 필터링 실습

행렬 분해 잠재 요인 협업 필터링: SVD, NMF 적용
- 사용자-아이템 평점 행렬에는 널 데이터가 많아 주로 **SGD, ALS** 기반의 행렬 분해 이용.

R: 원본 사용자-아이템 평점 행렬

K: 잠재 요인의 차원 수

steps: SGD의 반복 횟수

learning_rate: 학습률

r_lambda: L2 규제 계수

## 08 파이썬추천 시스템 패키지 - Surprise

### Surprise 패키지 소개

Surprise: 파이썬 기반의 추천 시스템 구축을 위한 전용 패키지
- 다양한 추천 알고리즘(아이템 기반 최근접 이웃 협업 필터링, SVD. SVD++, NMF 기반의 잠재 요인 협업 필터링)을 적용해 추천 시스템 구축 가능.
- 사이킷런의 핵심 API와 유사한 API명.

### Surprise를 이용한 추천 시스템 구축

주요 데이터가 로우 레벨 형태로 되어 있는 포맷의 데이터만을 처리함.

자체적으로 로우 레벨의 데이터를 칼럼 레벨의 데이터로 변경하므로 원본인 로우 레벨의 사용자-아이템 평점 데이터를 데이터 세트로 적용해야 함.

algo=SVD()에 fit(학습 데이터 세트) 수행

test(): 사용자-아이템 평점 데이터 세트 전체에 대해 추천을 예측하는 메서드. 입력된 데이터 세트에 대해 추천 데이터 세트를 만듦. 입력 데이터 세트의 모든 사용자와 아이템 아이디에 대해 predict()를 반복적으로 수행한 결과.

predict(): 개별 사용자와 영화에 대한 추천 평점 반환. 인자로 개별 사용자 아이디, 아이템 아이디를 입력.(> 추천 예측 평점을 포함한 정보를 est로 반환.)

### Surprise 주요 모듈 소개

#### Dataset

#### OS 파일 데이터를 Surprise 데이터 세트로 로딩

Dataet.load_builtin

Dataset.load_from_file(file_path,reader): OS 파일에서 데이터를 로딩할 때 사용.

Dataset.load_from_df(df,reader): 판다스의 DataFrame에서 데이터를 로딩.

#### 판다스 DataFrame에서 Surprise 데이터 세트로 로딩

로딩되는 데이터 파일에 칼럼명을 가지는 헤더 문자열이 있으면 안 됨. -> 칼럼 헤더가 있을 시 헤더를 삭제해 csv로 저장한 뒤 로드.
- Reader 클래스의 생성자에 각 필드의 칼럼명, 칼럼 분리문자, 최소~최대 평점을 입력해 객체 생성.

**Reader 클래스 주요 생성 파라미터**
- line_format(str): 칼럼을 순서대로 나열.
- sep(char): 칼럼을 분리하는 분리자. 디폴트='\t'
- rating_scale(tuple,optional): 평점 값의 최소~최대 평점 설정.

### Surprise 추천 알고리즘 클래스

SVD: 행렬 분해를 통한 잠재 요인 협업 필터링을 위한 SVD 알고리즘

KNNBasic: 최근접 이웃 협업 필터링을 위한 KNN 알고리즘.

BaselineOnly: 사용자 Bias와 아이템 Bias를 감안한 SGD 베이스라인 알고리즘.

**SVD 클래스의 입력 파라미터**
- n_factors: 잠재 요인 K 개수
- n_epochs: SGD 수행 시 반복 횟수
- biased: 베이스라인 사용자 편향 적용 여부

### 베이스라인 평점

개인의 성향을 반영해 아이템 평가에 편향성(bias) 요소를 반영하여 평점을 부여하는 것.

베이스라인 평점 = 전체 평균 평점 + 사용자 편향 점수 + 아이템 편향 점수
- 전체 평균 평점: 모든 사용자의 아이템에 대한 평점을 평균한 값.
- 사용자 편향 점수: 사용자별 아이템 평점 평균 값 - 전체 평균 평점
- 아이템 편향 점수: 아이템별 평점 평균 값 - 전체 평균 평점

### 교차 검증과 하이퍼 파라미터 튜닝

cross_validate(): 폴드된 데이터 세트의 개수와 성능 측정 방법을 명시해 교차 검증 수행. - 알고리즘 객체, 데이터, 성능 평가 방법, 폴드 데이터 세트 개수 입력.

GridSearchCV: 교차 검증을 통한 하이퍼 파라미터 최적화 수행. n_epochs, n_factors 튜닝.

### Surprise를 이용한 개인화 영화 추천 시스템 구축

## 09 정리

추천 시스템: 콘텐츠 기반 필터링, 협업 필터링

콘텐츠 기반 필터링: 아이템을 구성하는 여러 가지 콘텐츠 중 사용자가 좋아하는 콘텐츠를 필터링하여 이에 맞는 아이템을 추천하는 방식.

협업 필터링: 최근접 이웃 협업 필터링, 잠재 요인 협업 필터링
- 최근접 이웃 협업 필터링: 사용자 기반(사용자-사용자), 아이템 기반(아이템-아이템)
- 잠재 요인 협업 필터링: 사용자-아이템 행렬 데이터에 숨어 있는 잠재 요인을 추출하여 사용자가 아직 평점을 매기지 않은 아이템에 대한 평점을 예측하여 추처에 반영. 행렬 분해 적용.

Surprise: 파이썬의 추천 시스템 패키지

# **[코드 필사]**

## 07. 행렬 분해를 이용한 잠재 요인 협업 필터링 실습

행렬 분해 잠재 요인 협업 필터링: SVD, NMF 적용
- 사용자-아이템 평점 행렬에는 널 데이터가 많아 주로 **SGD, ALS** 기반의 행렬 분해 이용.

R: 원본 사용자-아이템 평점 행렬

K: 잠재 요인의 차원 수

steps: SGD의 반복 횟수

learning_rate: 학습률

r_lambda: L2 규제 계수

In [ ]:
import numpy as np

def get_rmse(R, P, Q, non_zeros):
    error = 0
    for i, j, r in non_zeros:
        pred = np.dot(P[i, :], Q[j, :].T)
        error += pow(r - pred, 2)
    rmse = np.sqrt(error / len(non_zeros))

    return rmse

In [ ]:
def matrix_factorization(R,K,steps=200,learning_rate=0.01,r_lambda=0.01):
  num_users,num_items=R.shape
  # P와 Q 매트릭스의 크기를 지정하고 정규 분포를 가진 랜덤한 값으로 입력합니다.
  np.random.seed(1)
  P=np.random.normal(scale=1./K,size=(num_users,K))
  Q=np.random.normal(scale=1./K,size=(num_items,K))

  # R>0인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장
  non_zeros=[(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if range(num_items) if R[i,j]>0]

  # SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
  for step in range(steps):
    for i,j,r in non_zeros:
      # 실제값과 예측값의 차이인 오류값 구함
      eij=r-np.dot(P[i,:],Q[j,:].T)
      # Regularization을 반영한 SGD 업데이트 공식 적용
      P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
      Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])

    rmse=get_rmse(R,P,Q,non_zeros)
    if (step % 10)==0:
      print("### iteration step : ",step," rmse : ",rmse)

  return P,Q

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
movies=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/movies.csv')
ratings=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/ratings.csv')
ratings=ratings[['userId','movieId','rating']]
ratings_matrix=ratings.pivot_table('rating',index='userId',columns='movieId')

# title 칼럼을 얻기 위해 movies와 조인 수행
rating_movies=pd.merge(ratings,movies,on='movieId')
# columns='title'로 title 칼럼으로 pivot 수행
ratings_matrix=rating_movies.pivot_table('rating',index='userId',columns='title')

In [ ]:
P,Q=matrix_factorization(ratings_matrix.values,K=50,steps=200,learning_rate=0.01,
                         r_lambda=0.01)
pred_matrix=np.dot(P,Q.T)

### iteration step :  0  rmse :  2.9023619751337115
### iteration step :  10  rmse :  0.7335768591017939
### iteration step :  20  rmse :  0.5115539026853438
### iteration step :  30  rmse :  0.37261628282537734
### iteration step :  40  rmse :  0.29608182991810145
### iteration step :  50  rmse :  0.2520353192341621
### iteration step :  60  rmse :  0.22487503275269882
### iteration step :  70  rmse :  0.20685455302331512
### iteration step :  80  rmse :  0.19413418783028674
### iteration step :  90  rmse :  0.1847008200272031
### iteration step :  100  rmse :  0.17742927527209082
### iteration step :  110  rmse :  0.17165226964707506
### iteration step :  120  rmse :  0.16695181946871496
### iteration step :  130  rmse :  0.16305292191997453
### iteration step :  140  rmse :  0.159766919296796
### iteration step :  150  rmse :  0.15695986999457337
### iteration step :  160  rmse :  0.15453398186715442
### iteration step :  170  rmse :  0.1524161855107769
### iteration step :  180  rmse :  0.1505508073962834
### iteration step :  190  rmse :  0.14889470913232075

In [ ]:
ratings_pred_matrix=pd.DataFrame(data=pred_matrix,index=ratings_matrix.index,
                                 columns=ratings_matrix.columns)
ratings_pred_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.055084,4.092018,3.564130,4.502167,3.981215,1.271694,3.603274,2.333266,5.091749,3.972454,...,1.402608,4.208382,3.705957,2.720514,2.787331,3.475076,3.253458,2.161087,4.010495,0.859474
2,3.170119,3.657992,3.308707,4.166521,4.311890,1.275469,4.237972,1.900366,3.392859,3.647421,...,0.973811,3.528264,3.361532,2.672535,2.404456,4.232789,2.911602,1.634576,4.135735,0.725684
3,2.307073,1.658853,1.443538,2.208859,2.229486,0.780760,1.997043,0.924908,2.970700,2.551446,...,0.520354,1.709494,2.281596,1.782833,1.635173,1.323276,2.887580,1.042618,2.293890,0.396941

In [ ]:
# 사용자 9번 영화추천
def get_unseen_movies(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 영화 정보를 추출해 Series로 반환함.
    # 반환된 user_rating은 영화명(title)을 인덱스를 가지는 Series 객체임.
    user_rating = ratings_matrix.loc[userId, :]

    #user_rating이 0보다 크면 기존에 관람한 영화임. 대상 인덱스를 추출해 list 객체로 만듦.
    already_seen = user_rating[ user_rating > 0].index.tolist()

    # 모든 영화명을 list 객체로 만듦.
    movies_list = ratings_matrix.columns.tolist()

    # list comporehension으로 already_seen에 해당하는 영화는 movies_list에서 제외함.
    unseen_list = [ movie for movie in movies_list if movie not in already_seen]

    return unseen_list

def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n = 10):
    # 예측 평점 DataFrame에서 사용자id 인덱스와 unseen_list로 들어온 영화명 칼럼을 추출해
    # 가장 예측 평점이 높은 순으로 정렬함.
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]

    return recomm_movies

In [ ]:
# 사용자가 관람하지 않은 영화명 추출
unseen_list=get_unseen_movies(ratings_matrix,9)

# 잠재 요인 협업 필터링으로 영화 추천
recomm_movies=recomm_movie_by_userid(ratings_pred_matrix,9,unseen_list,top_n=10)

# 평점 데이터를 DataFrame으로 생성
recomm_movies=pd.DataFrame(data=recomm_movies.values,index=recomm_movies.index,columns=['pred_score'])
recomm_movies

                                                    pred_score
title
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601

## 08 파이썬추천 시스템 패키지 - Surprise

### Surprise 패키지 소개

Surprise: 파이썬 기반의 추천 시스템 구축을 위한 전용 패키지
- 다양한 추천 알고리즘(아이템 기반 최근접 이웃 협업 필터링, SVD. SVD++, NMF 기반의 잠재 요인 협업 필터링)을 적용해 추천 시스템 구축 가능.
- 사이킷런의 핵심 API와 유사한 API명.

In [3]:
! pip install "numpy<2"

Collecting numpy<2
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.5 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 84.8 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [1]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2554978 sha256=78af22b37cd02d4c3d06474e63f3d1f7788dde4d088e43132f3368e86c8e8d2e
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [ ]:
# ! conda install -c conda-forge scikit-surprise

/bin/bash: line 1: conda: command not found

### Surprise를 이용한 추천 시스템 구축

주요 데이터가 로우 레벨 형태로 되어 있는 포맷의 데이터만을 처리함.

자체적으로 로우 레벨의 데이터를 칼럼 레벨의 데이터로 변경하므로 원본인 로우 레벨의 사용자-아이템 평점 데이터를 데이터 세트로 적용해야 함.

algo=SVD()에 fit(학습 데이터 세트) 수행

test(): 사용자-아이템 평점 데이터 세트 전체에 대해 추천을 예측하는 메서드. 입력된 데이터 세트에 대해 추천 데이터 세트를 만듦. 입력 데이터 세트의 모든 사용자와 아이템 아이디에 대해 predict()를 반복적으로 수행한 결과.

predict(): 개별 사용자와 영화에 대한 추천 평점 반환. 인자로 개별 사용자 아이디, 아이템 아이디를 입력.(> 추천 예측 평점을 포함한 정보를 est로 반환.)

In [1]:
!pip uninstall numpy -y
!pip install numpy==1.26.6
!pip install scikit-surprise --upgrade --no-deps

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
ERROR: Ignored the following yanked versions: 2.4.0
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement numpy==1.26.6 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0rc1, 2.4.1, 2.4.2, 2.4.3)
ERROR: No matching distribution found for numpy==1.26.6
Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)

In [3]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

In [4]:
data=Dataset.load_builtin('ml-100k')
# 수행 시마다 동일하게 데이터를 분할하기 위해 random_state 값 부여
trainset,testset=train_test_split(data,test_size=.25,random_state=0)

Dataset ml-100k could not be found. Do you want to download it? [Y/n] Y
Trying to download dataset from https://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k

In [5]:
algo=SVD(random_state=0)
algo.fit(trainset)

In [6]:
predictions=algo.test(testset)
print('prediction type : ',type(predictions),'size : ',len(predictions))
print('prediction 결과의 최초 5개 추출')
predictions[:5]

prediction type :  <class 'list'> size :  25000
prediction 결과의 최초 5개 추출

[Prediction(uid='120', iid='282', r_ui=4.0, est=3.5114147666251547, details={'was_impossible': False}),
 Prediction(uid='882', iid='291', r_ui=4.0, est=3.573872419581491, details={'was_impossible': False}),
 Prediction(uid='535', iid='507', r_ui=5.0, est=4.033583485472447, details={'was_impossible': False}),
 Prediction(uid='697', iid='244', r_ui=5.0, est=3.8463639495936905, details={'was_impossible': False}),
 Prediction(uid='751', iid='385', r_ui=4.0, est=3.1807542478219157, details={'was_impossible': False})]

In [7]:
[(pred.uid,pred.iid,pred.est) for pred in predictions[:3]]

[('120', '282', 3.5114147666251547),
 ('882', '291', 3.573872419581491),
 ('535', '507', 4.033583485472447)]

In [8]:
# 사용자 아이디, 아이템 아이디는 문자열로 입력해야 함
uid=str(196)
iid=str(302)
pred=algo.predict(uid,iid)
print(pred)

user: 196        item: 302        r_ui = None   est = 4.49   {'was_impossible': False}

In [9]:
accuracy.rmse(predictions)

RMSE: 0.9467

0.9466860806937948

### Surprise 주요 모듈 소개

#### Dataset

#### OS 파일 데이터를 Surprise 데이터 세트로 로딩

Dataet.load_builtin

Dataset.load_from_file(file_path,reader): OS 파일에서 데이터를 로딩할 때 사용.

Dataset.load_from_df(df,reader): 판다스의 DataFrame에서 데이터를 로딩.

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [17]:
import pandas as pd

ratings=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/ratings.csv')
# ratings_noh.csv 파일 언로드 시 인덱스와 헤더를 모두 제거한 새로운 파일 생성.
ratings.to_csv('/content/drive/MyDrive/Colab/ESAA/ratings_noh.csv',index=False,header=False)

In [18]:
from surprise import Reader
from surprise import Dataset

reader=Reader(line_format='user item rating timestamp',sep=',',rating_scale=(0.5,5))
data=Dataset.load_from_file('/content/drive/MyDrive/Colab/ESAA/ratings_noh.csv',reader=reader)

In [19]:
trainset,testset=train_test_split(data,test_size=0.25,random_state=0)

# 수행 시마다 동일한 결과를 도출하기 위해 random_state 설정
algo=SVD(n_factors=50,random_state=0)

# 학습 데이터 세트로 학습하고 나서 테스트 데이터 세트로 평점 예측 후 RMSE 평가
algo.fit(trainset)
predictions=algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682

0.8681952927143516

#### 판다스 DataFrame에서 Surprise 데이터 세트로 로딩

로딩되는 데이터 파일에 칼럼명을 가지는 헤더 문자열이 있으면 안 됨. -> 칼럼 헤더가 있을 시 헤더를 삭제해 csv로 저장한 뒤 로드.
- Reader 클래스의 생성자에 각 필드의 칼럼명, 칼럼 분리문자, 최소~최대 평점을 입력해 객체 생성.

**Reader 클래스 주요 생성 파라미터**
- line_format(str): 칼럼을 순서대로 나열.
- sep(char): 칼럼을 분리하는 분리자. 디폴트='\t'
- rating_scale(tuple,optional): 평점 값의 최소~최대 평점 설정.

In [21]:
import pandas as pd
from surprise import Reader,Dataset

ratings=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/ratings.csv')
reader=Reader(rating_scale=(0.5,5))

# ratings DataFrame에서 칼럼은 사용자 아이디, 아이템 아이디, 평점 순서를 지켜야 합니다.
data=Dataset.load_from_df(ratings[['userId','movieId','rating']],reader)
trainset,testset=train_test_split(data,test_size=0.25,random_state=0)

algo=SVD(n_factors=50,random_state=0)
algo.fit(trainset)
predictions=algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682

0.8681952927143516

### Surprise 추천 알고리즘 클래스

SVD: 행렬 분해를 통한 잠재 요인 협업 필터링을 위한 SVD 알고리즘

KNNBasic: 최근접 이웃 협업 필터링을 위한 KNN 알고리즘.

BaselineOnly: 사용자 Bias와 아이템 Bias를 감안한 SGD 베이스라인 알고리즘.

**SVD 클래스의 입력 파라미터**
- n_factors: 잠재 요인 K 개수
- n_epochs: SGD 수행 시 반복 횟수
- biased: 베이스라인 사용자 편향 적용 여부

### 베이스라인 평점

개인의 성향을 반영해 아이템 평가에 편향성(bias) 요소를 반영하여 평점을 부여하는 것.

베이스라인 평점 = 전체 평균 평점 + 사용자 편향 점수 + 아이템 편향 점수
- 전체 평균 평점: 모든 사용자의 아이템에 대한 평점을 평균한 값.
- 사용자 편향 점수: 사용자별 아이템 평점 평균 값 - 전체 평균 평점
- 아이템 편향 점수: 아이템별 평점 평균 값 - 전체 평균 평점

### 교차 검증과 하이퍼 파라미터 튜닝

cross_validate(): 폴드된 데이터 세트의 개수와 성능 측정 방법을 명시해 교차 검증 수행. - 알고리즘 객체, 데이터, 성능 평가 방법, 폴드 데이터 세트 개수 입력.

GridSearchCV: 교차 검증을 통한 하이퍼 파라미터 최적화 수행. n_epochs, n_factors 튜닝.

In [22]:
from surprise.model_selection import cross_validate

# 판다스 DataFrame에서 Surprise 데이터 세트로 데이터 로딩
ratings=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/ratings.csv') # reading data in pandas df
reader=Reader(rating_scale=(0.5,5.0))
data=Dataset.load_from_df(ratings[['userId','movieId','rating']],reader)

algo=SVD(random_state=0)
cross_validate(algo,data,measures=['RMSE','MAE'],cv=5,verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.8708  0.8715  0.8794  0.8641  0.8811  0.8734  0.0062
MAE (testset)     0.6680  0.6668  0.6750  0.6651  0.6779  0.6706  0.0050
Fit time          1.54    1.39    1.45    1.38    2.10    1.57    0.27
Test time         0.11    0.26    0.13    0.10    0.18    0.15    0.06

{'test_rmse': array([0.87083535, 0.87148682, 0.87935248, 0.86411455, 0.88110306]),
 'test_mae': array([0.6680225 , 0.66683397, 0.67499704, 0.66513039, 0.67787309]),
 'fit_time': (1.5360925197601318,
  1.392514705657959,
  1.4452879428863525,
  1.3841094970703125,
  2.1040520668029785),
 'test_time': (0.10767245292663574,
  0.2561354637145996,
  0.1272144317626953,
  0.1049034595489502,
  0.17870688438415527)}

In [23]:
from surprise.model_selection import GridSearchCV

# 최적화할 파라미터를 딕셔너리 형태로 지정
params_grid={'n_epochs':[20,40,60],'n_factors':[50,100,200]}

# CV를 3개 폴드 세트로 지정, 성능 평가는 rmse, mse로 수행하도록 GridSearchCV 구성
gs=GridSearchCV(SVD,param_grid=params_grid,measures=['rmse','mae'],cv=3)
gs.fit(data)

# 최고 RMSE Evaluation 점수와 그때의 하이퍼 파라미터
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.8764315874615161
{'n_epochs': 20, 'n_factors': 50}

### Surprise를 이용한 개인화 영화 추천 시스템 구축

In [25]:
data=Dataset.load_from_df(ratings[['userId','movieId','rating']],reader)
trainset = data.build_full_trainset() # DatasetAutoFolds 객체를 Trainset으로 변환
algo=SVD(n_factors=50,random_state=0)
algo.fit(trainset)

In [28]:
from surprise import Reader, Dataset # DatasetAutoFolds 대신 Dataset을 직접 사용

reader=Reader(line_format='user item rating timestamp',sep=',',rating_scale=(0.5,5))
# Dataset.load_from_file()을 사용하여 파일에서 데이터셋 로드
data=Dataset.load_from_file('/content/drive/MyDrive/Colab/ESAA/ratings_noh.csv',reader=reader)

# 전체 데이터를 학습 데이터로 생성함
trainset=data.build_full_trainset()

In [29]:
algo=SVD(n_epochs=20,n_factors=50,random_state=0)
algo.fit(trainset)

In [31]:
# 영화에 대한 상세 속성 정보 DataFrame 로딩
movies=pd.read_csv('/content/drive/MyDrive/Colab/ESAA/movies.csv')

# userId=9의 movieId 데이터를 추출해 movieId=42 데이터가 있는지 확인
movieIds=ratings[ratings['userId']==9]['movieId']
if movieIds[movieIds==42].count()==0:
  print('사용자 아이디 9는 영화 아이디 42의 평점 없음')

print(movies[movies['movieId']==42])

사용자 아이디 9는 영화 아이디 42의 평점 없음
    movieId                   title              genres
38       42  Dead Presidents (1995)  Action|Crime|Drama

In [32]:
uid=str(9)
iid=str(42)

pred=algo.predict(uid,iid,verbose=True)

user: 9          item: 42         r_ui = None   est = 3.13   {'was_impossible': False}

In [33]:
def get_unseen_surprise(ratings,movies,userId):
  # 입력값으로 들어온 userId에 해당하는 사용자가 평점을 매긴 모든 영화를 리스트로 생성
  seen_movies=ratings[ratings['userId']==userId]['movieId'].tolist()

  # 모든 영화의 movieId를 리스트로 생성
  total_movies=movies['movieId'].tolist()

  # 모든 영화의 movieId 중 이미 평점을 매긴 영화의 movieId를 제외한 후 리스트로 생성
  unseen_movies=[movie for movie in total_movies if movie not in seen_movies]
  print('평점 매긴 영화 수:',len(seen_movies),'추천 대상 영화 수:',len(unseen_movies),
        '전체 영화 수:',len(total_movies))

  return unseen_movies

unseen_movies=get_unseen_surprise(ratings,movies,9)

평점 매긴 영화 수: 46 추천 대상 영화 수: 9696 전체 영화 수: 9742

In [34]:
def recomm_movie_by_surprise(algo,userId,unseen_movies,top_n=10):

  # 알고리즘 객체의 predict() 메서드를 평점이 없는 영화에 반복 수행한 후 결과를 list 객체로 저장
  predictions=[algo.predict(str(userId),str(movieId)) for movieId in unseen_movies]

  # predictions list 객체는 surprise의 Predictions 객체를 원소로 가지고 있음
  # [Prediction(uid='9',iid='1',est=3.69),Prediction(uid='9',iid='2',est=2.98),,,,]

  # 이를 est 값으로 정렬하기 위해서 아래의 sortkey_est 함수를 정의함
  # sortkey_est 함수는 list 객체의 sort() 함수의 키 값으로 사용되어 정렬 수행.
  def sortkey_est(pred):
    return pred.est

  # sortkey_est() 반환값의 내림차순으로 정렬 수행하고 top_n개의 최상위 값 추출
  predictions.sort(key=sortkey_est,reverse=True)
  top_predictions=predictions[:top_n]

  # top_n으로 추출된 영화의 정보 추출, 영화 아이디, 추천 예상 평점, 제목 추출
  top_movie_ids=[int(pred.iid) for pred in top_predictions]
  top_movie_rating=[pred.est for pred in top_predictions]
  top_movie_titles=movies[movies.movieId.isin(top_movie_ids)]['title']

  top_movie_preds=[(id,title,rating) for id,title,rating in zip(top_movie_ids,top_movie_titles,top_movie_rating)]

  return top_movie_preds

unseen_movies=get_unseen_surprise(ratings,movies,9)
top_movie_preds=recomm_movie_by_surprise(algo,9,unseen_movies,top_n=10)

print('##### Top-10 추천 영화 리스트 #####')
for top_movie in top_movie_preds:
  print(top_movie[1],":",top_movie[2])

평점 매긴 영화 수: 46 추천 대상 영화 수: 9696 전체 영화 수: 9742
##### Top-10 추천 영화 리스트 #####
Usual Suspects, The (1995) : 4.306302135700814
Star Wars: Episode IV - A New Hope (1977) : 4.281663842987387
Pulp Fiction (1994) : 4.278152632122759
Silence of the Lambs, The (1991) : 4.226073566460876
Godfather, The (1972) : 4.1918097904381995
Streetcar Named Desire, A (1951) : 4.154746591122657
Star Wars: Episode V - The Empire Strikes Back (1980) : 4.122016128534504
Star Wars: Episode VI - Return of the Jedi (1983) : 4.108009609093436
Goodfellas (1990) : 4.083464936588478
Glory (1989) : 4.07887165526957

## 09 정리

추천 시스템: 콘텐츠 기반 필터링, 협업 필터링

콘텐츠 기반 필터링: 아이템을 구성하는 여러 가지 콘텐츠 중 사용자가 좋아하는 콘텐츠를 필터링하여 이에 맞는 아이템을 추천하는 방식.

협업 필터링: 최근접 이웃 협업 필터링, 잠재 요인 협업 필터링
- 최근접 이웃 협업 필터링: 사용자 기반(사용자-사용자), 아이템 기반(아이템-아이템)
- 잠재 요인 협업 필터링: 사용자-아이템 행렬 데이터에 숨어 있는 잠재 요인을 추출하여 사용자가 아직 평점을 매기지 않은 아이템에 대한 평점을 예측하여 추처에 반영. 행렬 분해 적용.

Surprise: 파이썬의 추천 시스템 패키지